import Link from 'next/link'
import './globals.css'
import { LoginCom, LogoutCom } from './LoginCom'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Navber/>
        <div className='screen'>
          {children}
        </div>
      </body>
    </html>
  )
}

async function Navber(){
  const session = await getServerSession(authOptions);
  return (
    <nav>
      <div style={{display: "flex"}}>
        <div className='nav_main'>
          <Link href={`/`} className='title'>QBank</Link>
          <a className='cutline'/>
          <Link href={`/list`}>Problem List</Link>
          {
            session ? 
            <>
              <a className='cutline'/>
              <Link href={`/new`}>New Problem</Link>
              <Link href={`/solved`}>Sovled Road</Link>
              <a className='cutline'/>
              <Link href={`/mypage/problem`}>My Problem</Link>
              <Link href={`/mypage/comment`}>My Comment</Link>
            </> : ""
          }
        </div>
      </div>
      { session ? <LogoutCom/> : <LoginCom/>}
    </nav>
  )
}

function Footer(){
  
}