import Link from 'next/link'
import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Navber/>
        {children}
      </body>
    </html>
  )
}

function Navber(){
  return (
    <nav>
      <div className='nav_main'>
        <Link href={`/`} className='title'>QBank</Link>
        <a className='cutline'/>
        <Link href={`/list`}>Problem List</Link>
        <Link href={`/rank`}>Solver Rank</Link>
      </div>
      <div className='auth'>
        Login
      </div>
    </nav>
  )
}